### ISSUE TITLE
Commit column disappears

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#100]
1. start the application
2. click on req number. result - all commits and corresponding files are displayed (OK!)
3. click on a file title. result - the file content is displayed, but the commit column is empty

expected:
the column "commit" displays commit(s), which affected the chosen file

**Comment by GnuTalux** [comment]
I found the issue.

It is due to missing implementaion of ```equals``` within class ```Commit``` which extends ```DataElements```.

@gayathery: I have implemented ```equals``` and now I see, that you also did it.
But your ```equals`` returns everytime ```False``` for equal commits (equal id and message).
I don't know, what your intention was to implement a pretty complex ```equal``` method, but
due to incorrect  ```instanceRequirement``` attribute, its not really working.

My approach is a eqauls method, which tests for equal id and message (but Id should be enough) ...
OR we should find out, why sometimes ```instanceRequirement``` is null and sometime not.

I have just out commented the ```instanceRequirement``` section. 
(please have a look at it)

**Comment by GnuTalux** [comment]
@gayathery Are changes I made in ```Commit.equals``` is ok for you?

**Comment by gayathery** [comment]
@GnuTalux   The problem that "instanceRequirement" is null sometimes and not null sometimes is little tricky. because even i saw this issue but the new UI architecture is so complex to modify something. I had seen that when user clicks on a requirement in the application, firstly there are a set of commitfiles list created which does not have impact and other data and there is no relationship existing at this point of time between requirement, commit and commitfiles, later another layer of code is called where again commitfiles are created which contains links between them. I was really confused about this UI architecture of why so many objects were created in runtime and then copied between layers.. As far as your changes to equals it does not have any problem to my implementation, but have to see whether it affects something else.. but until we do not get issues, let the equals of yours be there :)

**Comment by GnuTalux** [comment]
thank you very much for your detailed and well explanation :-)

I think, at worst I can solve this issue without the need of this changes in ```equals```,
but I am not really sure, if that is really better then ^^ ...

but I would let it as it is, too :-)

**Comment by KatsiarynaK** [comment]
Hi everyone! 

I just made the build and I can see that the problem is in

http://gyazo.com/9654706653e085841f545239acbd8e7d

**Comment by TPolzer** [comment]
Is this the same defect as #91? @yadimon?

**Comment by GnuTalux** [comment]
the bug letting commit entries disappear was in ```Collection_Model_Impl::commitsFromRequirementAndFile```.
```Collection::retainAll``` was used to get the intersecting commit of the set of commits of a given reqId and a filepath.
In this case ```GitVcsClient.java#getCommitListForFileodification()``` returned a set of commits, 
without a proper equals-method, it was not able to get a intersecting set of commits.

the bug of #91 is still living, perhaps.


Can anyone check my changes, if this is working now? @KatsiarynaK

**Comment by gayathery** [comment]
@GnuTalux I tried but there is one problem. the following doesnt work

1. select requirement
2. now commits and files appear in the respective columns
3. Now click file (commits are still there...and this bug is fixed now)
4. Now click the commit - the files are not shown respective to the commit--this is a problem

**Comment by KatsiarynaK** [comment]
@GnuTalux Yes, agree with @gayathery , the initial bug is fixed, but there is a new one, described above

**Comment by GnuTalux** [comment]
I will try to work on it :)

**Comment by KatsiarynaK** [comment]
Fixed
