### ISSUE TITLE
new blame in eclipse

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#107]
In my testing eclipse still calculates blame the old style.

@gayathery agreed to debug this.

**Comment by gayathery** [comment]
In order to reflect the changes in each builds, 

1 . Uninstall the current plugin installation.
2. Check if amos-ss15-proj3-eclipse-plugin_1.0.0.jar is deleted in eclipse / plugins folder manually.
3. Before installing new plugin - clear the maven repository - in .m2\repository\de
4. Now proceed with the plugin installation.

**Comment by TPolzer** [comment]
Why do you clean the maven repository? Nothing in there is executed by the eclipse plugin I think?

**Comment by gayathery** [comment]
Untill we upgrade our version number eclipse thinks its same version of the
plugin.
