### ISSUE TITLE
please, could anyone check branch "Req-68_link_moved_file"...

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#148]
please, could anyone check branch "Req-68_link_moved_file", whether user story is correctly implemented.
6c281b3ede298dc124e9158625eda414dc8cd5cf

User story 68

**Comment by gayathery** [comment]
i checked it, the basic functionality is not working. first of all there is problem in maven building,. because visiblefiletraversertest is failing. The list of file are not shown for any requirement and lot of background exceptions are thrown for some cases. there are also problem with file paths.

**Comment by KatsiarynaK** [comment]
@gayathery thanks for checking. 
Actually, I am mot sure how I could check the user story. Of course, I could move any file to a new folder, but I am not sure what affect it would have done on the project.

**Comment by gayathery** [comment]
@KatsiarynaK i did not actually check the user story, but it actually this branch at its existing state had lot of problems with existing feature itself. so i thought there was no point in checking further

1. maven build was failing because of a test failure
2. i removed the test and then compiled and then checked the feature
3. when requirement is clicked commits are listed but no commit files are shown
4. there are many background exception being thrown at many point of usage of application

i raised an issue regarding to the performance problems in our application. https://github.com/uv48uson/amos-ss15-proj3/issues/155.

The two methods that are listed in issue 155 are the main bottle necks for the performance

@GnuTalux  hope you could clarify more

**Comment by GnuTalux** [comment]
now it should work.

floh and I checked it ;-)
