### ISSUE TITLE
Checked exceptions?

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#27]
I just stumbled over the `throws Exception` in DataSource.java. I think we need to discuss how we want to handle checked exceptions. As I see it there two possible ways (feel free to suggest alternatives), but we should agree on a single one:
- Have no checked exceptions in our code at all, if we happen to catch one from a library and cannot handle it reasonably at that point, rethrow it as a RuntimeException.
- declare possible exceptions, e.g. `throws IOException`.

Also please have a look at https://today.java.net/article/2006/04/04/exception-handling-antipatterns#throwingException
and https://today.java.net/article/2006/04/04/exception-handling-antipatterns#logAndReturnNull

**Comment by uv48uson** [comment]
I think the second one is fine. In generall we want to use the exceptions to inform higher located classes to about some kind of missuse. In this case we should throw the excption and catch it later(in the gui controller f.e.) were we can handle it. -> reinform user or decide whether the system should terminate. But if the exception occurs due to some internal error(well im missusing "error" here) it should be some kind of errror/runtimeexception(or rethrow it as one) which can not be handled anywhere. 
I'll try to push the refactored gui today or tommorrow morning. There the exception handling how i just explained it is already implemented.

**Comment by GnuTalux** [comment]
I also wondered about the """throws Exception""" things.
As I wrote the DataRetriever-Methods for the GUI, I handled the Exceptions within the same method.
But I was not happy about it :smile: 

What I don't really understand is, why are the ```throws Exception``` statements defined with in the interface. 
I think, Exceptions like ```RelationNotFound``` (...)  would be more reasonable... but in that case I would just return a "Empty"-Value in respect to the certain data type.

**Comment by uv48uson** [comment]
take a look at the refactored UI in Branch Req-17

**Comment by yadimon** [comment]
If the database throws an exception, that means, the results are broken. So what the user will see is already bad. That why "return null" or something like this is bad on such low lvl implementations. (but still make since in some situations)
*the nice article says about it
The interface/abstract class (DataSource) must throw some general exception, because we dont know the implementation. But IOExceprion should cover all the cases i think. I am for the second solution too.
The UI or some our frontend clients, should handle the exceptions.
To declare our own exceptions could be good, for example for some LastLevel/API class, like Tracker for now, so that the frontend-client knows whats really going on, and can handle it.

**Comment by uv48uson** [comment]
normally returning null is not a good choice. If there is no data just return an empty collection for example. This shouldn't cause any exception. 
Yes I agree that if the results are somehow broken an exception should be thrown.

**Comment by GnuTalux** [comment]
Returning an "empty" of a datatype is mostly the good choice.
In Python (for example) this is default.
But I think, we have discussed this in an other issue.
