### ISSUE TITLE
Unified source for linkage?

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#28]
I just started working on Req-11 and I was a little confused by the existing hierarchy around DataSource and DataRetriever. Can somebody please explain this to me? Will this change?

**Comment by uv48uson** [comment]
I'll try to push the refactored gui today or tommorrow morning. Then u can have a closer look at it. However this will hardly change the dataretriever. In generall the DataRetriever was created as some kind of interface for our libary (facade pattern). Concerning the interaction with datasource, we already discussed between taleh, gayerthery and me, that we should change the interaction somehow.

**Comment by TPolzer** [comment]
To be honest, using a DataRetriever to get Requirements for a single commit seems very weird to me, it uses a Tracker which has nothing to do with the functionality needed to get linkage!

I thought the general direction we wanted was some kind ob interface / abstract class that specifies how a source / sink of linkage looks (e.g. DataSource) and then we have a class that aggregates several of those sources and is itself again a source (so it extends DataSource or something similar).

**Comment by GnuTalux** [comment]
The Tracker-Class provides a abstraction for getting ReqID and CommitID relations, but DataRetriever somehow does the same. Currently DataRetriever uses DataSource, which return PostTraceability... I will change this.

Gayathery, Dimitry an I had a disscussion about this problem. 
@gayathery, @udimon...
Did we come to a final solution?

**Comment by TPolzer** [comment]
Tracker provides an abstraction of the linkage commit<->req to file<->req, but that is absolutely not needed for aggregating the raw linkage, that should happen "below" Tracker.

**Comment by GnuTalux** [comment]
@TPolzer Do you prefer a additional abstraction for different "data sources"?

from what I understand, Tracker retrieves commit<->req information via ```jgit``` by reading out a repo and ```DataSource``` from post traceability...

Do we really need a further abstraction layer? Somehow this can be clever, but then we doesn't need the DataRetriever? 

@uv48uson The GUI is using DataSource for getting commit<->req info. But this will just return post traceability. I should change this to Tracker. But Tracker doesn't provide any "add post traceabiltiy relation".  I would fix this, but I am not sure, what our Team is thinking about this. 

@gayathery, @yadimon

**Comment by TPolzer** [comment]
@GnuTalux I would prefer not to have an _additional_ abstraction layer but to have some _well structured_ abstraction, because right now it all looks a little chaotic.

@yadimon Didn't you draw a diagram of how you thought this should look?

**Comment by uv48uson** [comment]
@TPolzer Seems like there is still a missunderstanding. Just ignore DataRetriever for now in your discussion: First of all DataRetriever will be updated tommorrow morning. Secondly DataRetriever is only a facade/interface for our whole functionality(there should be no logic in here; if there is (tommorrow) just write a bug fix issue. Or if somebody used the wrong classes to recieve the data from lower classes.

@GnuTalux I dont mind if u change what dataretriever does intern. Its the responsibility of whoever changes the underlying classes or there functionality that the methods are still fullfilling there purpose.

**Comment by gayathery** [comment]
I had suggested that not to expose any datasource calls in the UI . Here
the dataretriver class.

Also any changes to UI framework shouldn't keep us changing the logic later
on.

Tracker is just aggregating the data from git repo and database to provide
one single result to the UI calls.

For now, I left a TODO, untill Taleh and Dmity refine something with tge
datasource lauer.

**Comment by uv48uson** [comment]
I pushed the refactored UI to Branch Req17.
I dont know what the tracker should do. If u can agree on taking it as a facade, im fine with it. If u dont ok. But until then there is no need to change the DataRetriever(now named Modell in Req17 UI Branch).
@TPolzer @yadimon please keep the discussion here not in studon.

**Comment by TPolzer** [comment]
Who is actually responsible right now for creating a single interface which enables others (like the functionality I am working on now) to get aggregated requirements for a single commit (from multiple sources)? @yadimon?

**Comment by yadimon** [comment]
As i understand after talking with Gayathery and Taleh, the Tracker is the last lvl (like "API") class. This class uses DataSource and combines it with VCS source, to return combined REQ - COMMIT linkage for example.
All persistent data should be got and saved over DataSource (the best way could be use the datasource only from tracker class, because its initialized there).
So the Tracker should use the combined data, and give what necessery to (any) UI over trackers methods.
The UI should instantiate the tracker with right DataSource and VCSController. (possible instantiation maybe higher lvl class in the future, or the tracker itself, by own methods).

**Comment by TPolzer** [comment]
If this is really what the Tracker was made for (I'm not sure), then why isn't the Tracker a DataSource?

**Comment by uv48uson** [comment]
Im fully irritated right now. I'll change the UI when u agreed on one way.

**Comment by yadimon** [comment]
The tracker cannot implement DataSource (if you mean it), because things like "save" are not defined than, we dont change .git. And from outside our API sould not give all methods of DataSource.

DataSource is only for our database "something", "get/save some useful information"

The Gui Modell (2 L ?) do what tracker should do. But has some wrong things like "get..FromDB" .. there must be no difference by Tracker. UI/Server wants "give me all references" or "give me all info about this file" or "give me all info about this requirement by this commit and file". And all this, should be methods of Tracker.java. The ORM could be easy way for it, but need to implemen many things.

So there must be no Model for Gui/Server/Console etc ..  all the data -logic, -combination, -getting -saving must be done in the tracker. The only UI specific things, could be saved on some UI specific model whatever.

So probably GUI branch should be mega refactored and like 50% moved to tracker :/

i ll implement some missing parts for tracker now.

**Comment by uv48uson** [comment]
I wasnt sure about this at all. But if u all agree that tracker should be our kind of facade/interface, then we can simple move methods from facade.java to tracker.java. That's all. So the UI itself should not really be touched by this.

**Comment by yadimon** [comment]
yes, i see your code, i ll merge Facade with Tracker. I am improving the Tracker now to achieve our "Lib + UI" like software.
nice UI btw.

**Comment by uv48uson** [comment]
Are u sure u want to merge this on the last sprint day? Could make some problems. But if u are confident in doing so.

**Comment by uv48uson** [comment]
well u did it. Nice work. Nevertheless tracker seems to be kind of overloaded. Some of the methods should be moved to vcsController for example. But this could be part of next sprint.
