### ISSUE TITLE
Structure of GUI?!

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#31]
Today I wanted to implement Req-9 (in the Req-9) and finish Req-11, this however turned out to be far more difficult than anticipated, because the GUI code seems to grow every day in several directions.

I spent most of my time fighting through the existing code, which looks to me quite over complicated. I understand that the Req-17 branch is not finished, however I have no idea how to implement GUI features on top of a quickly moving target.

**Comment by TPolzer** [comment]
When will the structure be fixed? And can we please adhere to the KISS principle?

**Comment by uv48uson** [comment]
I'm working on the UI every day. So it changes every day. However i think it is not complex at all. I refactored everything past the last meeting. There are 3 very simple Patterns used, the structure is very clean,coupling very low and comments in for the main methods. 
Nevertheless i can understand, that it's not that easy for u to integrate a new feature due to a lot of new stuff u have to go through. Therefore i recommend (as discussed in meeting) to create a task for me and provide a simple interface called in ```Facade.java```

**Comment by uv48uson** [comment]
I merged Req-017 GUI Branch with master. This should help. Nevertheless we will have conflicts tommorrow. That's how it goes if multiple people are working on the same feature.

**Comment by TPolzer** [comment]
@uv48uson could you please try to merge my Req-11 branch into master?

**Comment by uv48uson** [comment]
seems like this is not that easy 
```
An internal error occurred during: "Merging with refs/remotes/origin/Req-11_highlight_linkage".
Exception caught during execution of merge command. org.eclipse.jgit.errors.NoMergeBaseException: No merge base could be determined. Reason=CONFLICTS_DURING_MERGE_BASE_CALCULATION. Multiple common ancestors were found and merging them resulted in a conflict: 1d06835af6eece7df693c6c6e7d8e3da83617c3c, 2f3a25ad62e17cb96d5ce09673c85227839299ad
```
I'll try again tommorrw.

**Comment by uv48uson** [comment]
@TPolzer I updated the test_branch_for_merge_commits Branch for manually merging brnach 11 to master. It's doable. Nevertheless i stopped my work for now, since i have deep doubts merging this code to master, after I had a closer look at it. I dont want to offend u, but the code u integrated seemed a bit chaotic for me. There are a lot of final variables which should not be final. There's going an a lot of stuff in other classes, where it should not be. Like Actionhandling in Controller, Modification of UI elements in adapter/facade ...

**Comment by TPolzer** [comment]
Local variables that are to be used in event handlers have to be final. And I used the structure the way it was when I was adding my code to the gui, yes the MVC seperation is a little bit muddy right now, but creating additional code in a MouseListener class that is tightly coupled to both View and Controller is not a better solution ;).

**Comment by uv48uson** [comment]
MVC seperation is not muddy at all. And the MouseListener only uses guiController. I'm working on the integration of your branch. Nevertheless, if u dont mind, i adapt it to the current architecture.

**Comment by TPolzer** [comment]
After the 'rewrite' we just did it should now work, but somehow nothing is displayed. I think you have more experience with Swing than I have, can you look into it?

**Comment by uv48uson** [comment]
done

**Comment by uv48uson** [comment]
nevertheless there seems to be a bug in catching the annotatedLines.
Req->File->Error for some files

**Comment by TPolzer** [comment]
fixed it.
