### ISSUE TITLE
For Sorting and Filtering

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#35]
For sorting and filtering we need the possibility to set/choose the sorting algorithm within the model.

As I understand the MVC architecture, the view provides something to select the sorting/filtering 
and the controller passes this "action" to model.
The Model knows the algorithm to sort/filter.

I have tried to understand our MVC implementation.
I am not sure, but could it be, that our Model-Interface doesn't allow passing/choosing a sorting/filter algorithm?

Depending to our current implementation, I could code a alphabetical sorting algorithm with in the ```GuiModel.getAllFiles()```.

What do you think guys, if we implement sorting and filtering algorithms which will be passed to Model as Sorting-/Filtering-Strategy (like Strategy-Pattern)?

But at first I would clarify how sorting/filtering should be passed to Model.
I think the easiest and maybe most "foolish" attempt is to extend the method signatures by sorting/filtering :see_no_evil:

**Comment by uv48uson** [comment]
Yes, I think extending is the way to go here. I did not intend to include the sorting that's why the architecture does not allow it right now. But u can simply change the getAllFiles signature for example and pass a strategy class. This would really ba a good archtiecture i think. Before this, there should be a user choise. like a drop down menue to choose the strategy. (this could be located over the file scrollbar, or in the menue. ). Whenever the user choses a new strategy an event is triggered and the new strategy object is stored in guiController. When showing the files the class is passed to the adapter. Please make sure, that if u change the sorting of the adapter, that u dont crash the current way to get commits and files by index. Maybe sort it and store the result afterwards in the commit/commitFiles Arrays. This should work.

**Comment by GnuTalux** [comment]
Ok. After class I will implement the architecture of Sorting/Filtering-Strategy-Classes.

**Comment by GnuTalux** [comment]
for info I am using following jre:
```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

If the software is not working on my machine, does this mean we are not releasing?
