### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#44]
For me some operations on the gui take really long. Like 10 sec ...
We should have a look at performance soon.

**Comment by gayathery** [comment]
i think this should really be looked upon....because getCommitFilesForRequirementID method is taking a long time even for one requirement..and if we generate a impact matrix for all requirements, it is really going to hang the system for hours

**Comment by gayathery** [comment]
I am really blocked to implement the impact traceability matrix because this method takes a long long time

**Comment by uv48uson** [comment]
this would really be easier with a database wouldn't it?
At least the getCommitFiles call to GitClient would be faster. I dont know yet what to do about the blame. Well, beside storing the blame result for the files once.

**Comment by gayathery** [comment]
database would not be nice for this because keeping the values in database consistent with Git is not easy

**Comment by yadimon** [comment]
things like getBlame, will take ever :)
because for each operation (any line) it need to ask all DataSources.
and any VcsDataSource request, means, load all repo.
thats why we should use database only (with loaded git data in it), at some time. But not now (as gayathery said, too hard)
For now, we can use req-commit-relation collection CACHE for performance. (me or someone can just implement it in abstract datasource)
and cache in VcsClient, to not go through all the git files for any request.

**Comment by gayathery** [comment]
I think we should plan to revert some code in this area because this performance issue is creating problems for our existing functionalities

**Comment by GnuTalux** [comment]
yeah, I also think a simple Cache within the VscClient could help us.

**Comment by KatsiarynaK** [comment]
Could you determine what new functionality slows down performance?

**Comment by gayathery** [comment]
The implementation using Blame for providing impact data is creating performance issues..in turn this functionality is required for other user stories to be completed

**Comment by KatsiarynaK** [comment]
@gayathery if the problem doesnt block you but only makes it inconvenient to work on the application, I thing that we can go on (at least this week). Additionally, we were told not to pay attention to the performance, so, 10 sec is stil ok. 

@yadimon @GnuTalux how long willl it take to implement Cache within the VscClient? Is any of you capable of doing it?

**Comment by yadimon** [comment]
@gayathery use mocks to test your code (Mockito, already included in our poject, see wiki for more information)
the mocks for datasource and VcsClient. So you will not need any perfromance of the real objects, and can simple make unit tests on your code.

**Comment by gayathery** [comment]
@KatsiarynaK 10 sec for one requirement ID is too much because for impact traceability matrix this time will be a multiple factor because matrix is for all requirements and files. and also 10 sec is only when there are less commits for a requirement ...or else it takes a long long time. I think this impact calculation should be done making using of threads from a defined thread pool

**Comment by gayathery** [comment]
@yadimon i already tested with a mock generated data...but i want to test them with real values..because some times the behavior can be different than what is expected. 

Also i saw one more possible issue in impact calculation. here a list of commit files is iterated in a loop and I think for impact calculation this will be  redundant  and it should not be so...
if in the list there is the following 
oldpath1 newpath1 modified commitid1
oldpath1 newpath1 modified commitid2

then these will be calculate impact for the same file twice

**Comment by gayathery** [comment]
traceability matrix working well with mock data butfor real data... i started the generation 40 minutes back and is not complete yet :(

**Comment by TPolzer** [comment]
I just did a quick bisect on this and 13df0d9107812ffd28751db81472e1b4594ebcc9 turned out to be the performance sink. The problem is that getting basic linkage commitId->[Req] is trivial to implement in a cheap way for all datasources and is used as a basic building block elsewhere (e.g. blame...), but right now getReqRelationByCommit iterates over the whole repository for each request.

**Comment by TPolzer** [comment]
Also a cache in VcsClient is not a going to help with anything. Git already implements lookup on commitIds.

**Comment by yadimon** [comment]
implemented cache (86d2548f8d14e27985154f62c1ba1f53a9f01328).
`Tracker::getAllReqCommitRelations()` now uses it.
if you need it directly from DataSource, use `DataSource::getCachedAllReqCommitRelations()` instead of `DataSource::getAllReqCommitRelations()`

**Comment by gayathery** [comment]
How much the performance improved after this cache implementation. ?

Please show your results

**Comment by yadimon** [comment]
I dont have any tests, but in theory there must be some improvement.
for good performance we need to cache vcsclient. (Tried it yesterday, but needed more than 30 mins, maybe today)

**Comment by GnuTalux** [comment]
@yadimon: When will the cache be updated?
Does it check for new commits?

**Comment by yadimon** [comment]
@GnuTalux by modifications (add/remove) see DataSource class.

**Comment by gayathery** [comment]
The problem in performance was because of the logic...changed the logic of the impact calculation and also fine tune some parameters being used in the loops... now the performance for the traceability matrix is improved from 19 minutes to 21 seconds. I have commited the changes along with my user story. and now the problem with the functionality is also fixed..with impact percentage being now calculated properly. one or two areas of fixes regarding to added and deleted files are pending but overall it is looking fine now
