### ISSUE TITLE
Bug in UI " Navigate from file "

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#45]
Navigate from file lists all files with some Impact percentage data , which is not appropriate.

Impact percentage should be shown only linking with requirements.

**Comment by GnuTalux** [comment]
I will fix this!

**Comment by GnuTalux** [comment]
in which branch should do this?
in a new one?

**Comment by gayathery** [comment]
if you have already a branch you can do it or create a new one

**Comment by uv48uson** [comment]
well for now i wanted to show it for every file because i wasnt sure in which situations it should be shown

**Comment by GnuTalux** [comment]
I have implemented it.
So that, if the user "navigates from files", then there is no highlighting and impact percentages. 
This was just a small change.

But I think in future it would be reasonable to show impact percentages and highlighting, if the user "navigates from files" and chooses a commit id.
