### ISSUE TITLE
Full traceability

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#78]
The first issue that was noticed that our traceability matrix contains a lot of 0 (zeroes). There are many requirements which were not reflected in source code files and vice versa, there are many source code files that don’t have any connection to any requirement. 
This is wrong.
The whole traceability logic implies that in order to implement EACH requirement AT LEAST one source code file was changed and EACH source code file was written based on AT LEAST  one requirement.

I was told that the reason why we have so many files without any connection to requirements is that the link between a commit and a requirement is deleted while a programmer merges his(or her) branch to the master (please, correct me if I misunderstood something). If so, that means that our work is basically deleted by making a merge. This is a serious problem, and our industry partner said that it actually blocks further implementation.

Therefore, first of all we need somehow resolve the situation with the absence of connections.

**Comment by uv48uson** [comment]
Hey,
first of all i totally agree to gayathery. github and skype if 
necerssary tommorrow(today) afternoon is fine.
Flo


Am 10.06.2015 um 23:11 schrieb KatsiarynaK:

**Comment by uv48uson** [comment]
It is not correct what u are saying. A merge does not delete anything. Moves are the problem. Thats the way i understood it until now. By the way, we were not concered about merges at all because so far u(i i sould say the industry partner) said we should concentrate on other things.

**Comment by uv48uson** [comment]
well mergeing could also be the problem because if both branches make modifications on the same file ...

**Comment by gayathery** [comment]
The problem is with moving of files and also when a line is modified for a requirement and later modified for a bug fix (the commit does not have a requirement  id) then the old info is lost because internally it means that the original line for the requirement is no more there in the current file.  Logically seeing it is correct. For example for Req 1 a set of lines could have been added and later point in time these lines could have been removed because of another requirement or a bug fix. So there can be a situation where for a requirement there is no line that is corresponding in the current code because all were deleted in some requirements that happened later to Req1

**Comment by gayathery** [comment]
I think this issue is mainly related to issue 79

**Comment by gayathery** [comment]
But if it is still required to give all requirements which influenced a file it is possible and in fact was our logic in the initial stage of our project.  The thing to keep in mind is. .in that case the results for a requirements will be referring to an old deleted file which is not there in the repository.

**Comment by TPolzer** [comment]
So much wrong information in one place.

- Merging is not an issue at all, it just looks that way in our current history, because we had merges where there were line ending style conflicts that were (presumably automatically) fixed (and that way "change" half the lines). At some point I gave up on convincing everybody to use unix style line endings.
- Moving is not a little bit of an issue, the requirements stay with the file, e.g. look at GitVcsClient.java, but navigating from requirement fails, because it looks for the file in the old path.
- That we have so many zeroes has two reasons:
  - The tracibility matrix lists files that do not exist anymore and therefore have no requirements attached at all.
  - We had some commits like "change tabs to spaces" that changed MANY lines and had no requirements attached, so obviously those files now have a zero.

**Comment by KatsiarynaK** [comment]
Glad to hear that merging is not a problem, it means that we can resolve the situation )) 

If you say that only the movement of file is the reason, than lets focus on this, because otherwise, the soft doesn’t provide required functionality of tracing requirements and their implementation.

Simple example:

User story #5 says that the linkage between file and commit must be in our software, indeed, it is present. But when I try to find any source code file that implemented the feature, I can not, because you moved them. 
Therefore, the soft must recognize such situations and keep the linkage.

About the matrix itself. 

The partner is happy with his simple way of matrix implementation (file to req correlation). 
Gayathery, you says that “then the old info is lost because internally it means that the original line for the requirement is no more there in the current file”. Yes, agree, this is correct in case if the line was deleted completely, but if it was only modified, the linkage should stay (but probably it is more related to issue #79).
Completely deleted files (NOT MOVED) should not be in traceability matrix, because they don’t have any value any more.
About the changing tabs (or changing anything else in the code line). We should keep info about a previous requirement, according to which the line was initially written. In this case, even if the file was changed without requirement, it still will have at least one linkage to the initial requirement (again, it is closely related to #79).

**Comment by GnuTalux** [comment]
I think, we are at a point, where massive usage of a database like dimitry suggested earlier, will be a solution.
To solve the "move" issue, we could iterate over every revision to track the changes.
So we can see, which file is moved or renamed... I am really confused, why git doesn't store renaming of files.
