### ISSUE TITLE
Code lines affected by several requirements

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#79]
The second problem we have is that when the file line was written because the req-1, and later on was changed by req-2, we only keep the information about the last requirement that affected the line. What the customer wants is that the req-1 and req-2 were displayed to the left of the affected code line.

**Comment by uv48uson** [comment]
not correct. else there would not exist a single line in any file with more than one req annotated. but there are

**Comment by TPolzer** [comment]
This is correct and not easily fixed because to fix this we would have to differentiate between changed and deleted lines.

**Comment by KatsiarynaK** [comment]
The recognition between changing and deleting lines is a core feature of the software, therefore, it must be implemented. 
Tobias, could you asses what should be done for it and how much efforts it required?

**Comment by TPolzer** [comment]
As I understood the industry partner at the first meeting this is actually not a core feature but something that can be thought about when the core features are working. Has this changed?

If we wanted some kind of word based blame there are several things that we would need to do:
- define what constitutes a word: not much effort but requires some thought
- insert line breaks between words in memory before executing the diff: this is some effort, if done wrong this could seriously harm performance
- In turn to do this we need our own blame logic, as already discussed, we are not sure how much effort this is (≥ 8 were our guesses) and I think the only way to really find out is to try. Although this provides us with no immediately obvious value we would gain a lot of flexibility here, so I suggest to just try, because without it all we can basically do now is polish what we have (should definitely be done, but maybe we want some more functionality).
- we would need to rethink how we are measuring impact when we assign blame to words instead of lines, again this is not much effort to implement but requires some thought

**Comment by GnuTalux** [comment]
sounds like a huge redesign.
How can I help?

**Comment by TPolzer** [comment]
Actually fixed for quite some time.
