### ISSUE TITLE
Wrong requirements order in the traceability matrix

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#97]
After the requirement 1 goes req 10, req 2 goes after 19 and before 20, etc.

**Comment by GnuTalux** [comment]
you mean, its unsorted?
As I see, requirement ids are generally unsorted.

**Comment by GnuTalux** [comment]
@yadimon: Didn't you fixed this?

**Comment by gayathery** [comment]
@KatsiarynaK  The sorting in Traceability matrix is automatic if sorting is done for the application- currently the sorting in "Navigate from requirement" is made as a integer sorting which is wrong because in real time it will be a combination of alphabets and strings.. So string sorting is the correct way

**Comment by yadimon** [comment]
@gayathery check sorting i used (9ab4616dbc017d30e13d4286f07c7ab7b3ee1e2f)

**Comment by gayathery** [comment]
@yadimon  thanks will add sorting to the matrix.

**Comment by KatsiarynaK** [comment]
@gayathery Sorry, I didnt really understand your message, therefore, I didnt reply. If it can wait till Monday, I would talk to you after POIS
